### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by danbri** [addshore/wikidata-query-now#1]
Could you stick an explicit license on the repo? https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository etc...?

**Comment by addshore** [comment]
Done as GPL for now.
I'd consider re-licensing if anyone has any specific needs.

**Comment by danbri** [comment]
Thanks! We lean towards Apache2 but GPL is fine
